### ISSUE TITLE
A quick question regarding the code.

### ISSUE THREAD

**Issue by avavinash** [blent-ai/ALEPython#2]
In line 123 of ale.py, you are subsetting the training data based on ith quantile interval ranges using :

`subset = train_set[(quantiles[i - 1] <= train_set[feature]) & (train_set[feature] < quantiles[i])]
`
Shouldn't it be quantiles[i - 1] **>=** train_set[feature]) instead of quantiles[i - 1] **<=** train_set[feature] ?

**Comment by scowan1995** [comment]
I think they have it correct. It basically gives you the values in the quantile that you're investigating. Your replacement would give you every value in the quantile below and you wouldn't even need any of the code past the & as anything less than q[i-1] is going to be less than q[i] .

**Comment by avavinash** [comment]
Yes, you are correct. Thanks!!!
